### PR TITLE
you need a sharper shrinkage!

### PR DESCRIPTION
**Pull request by donotdespair**
Hey @mantihuang 

I propose to generate results using a much sharper shrinkage for the `A` matrix. This usually helps to constrain explosive IRFs. 

You could try with different values for `kappa.1` :) That's why we estimate the shrinkage parameter - that is - to avoid the grid search until things go well. But maybe you'll be lucky the first time!

Let me know how it works :a:

### CODE REVIEW

**Comment by mantihuang** [comment]
Hi @donotdespair 

I have tried different kappa.1, but the plot still looks weird. 4ea9a07a6a19e7d82df8d52b04f75a2da95dc40f

Any suggestions on this issue will be appreciated ~

Thanks

**Comment by donotdespair** [comment]
Hey @mantihuang 

I need more details. What values of `kappa.1` have you tried? How did they change the IRFs values (not the shape only)?

This also can be the case that something is wrong in the other part of the code that causes this. We need to do sufficient testing that will allow us to figure out what's going on. And improve this aspect. That's an unavoidable part of code development (and it's the worst!). But if we want to have something new and original, we have go through this stage as well.

Good luck!

T

**Comment by mantihuang** [comment]
Hey @donotdespair 

I've tried several value of kappa.1, from 0.01 to my latest committed value. ! And also several values in between. The plot is updated in my website.

As for the code,I first transformed the B0 B1 to A and B. Then I use your code from lecture 12 for the irf plotting and specify that the first shock is the government spending shock.

Thank you for your prompt response.

Best,
Manting

**Comment by mantihuang** [comment]
Hi @donotdespair 

I have tried 

1. Keep the real exchange rate as the original and take log of other variables

 The code never stops.


2. Drop the RealTWI and add exports and imports to identify the shock 

It works 


I think it might be the variable real change rate that causes the explosive irf .

Please advise next steps.

Thank you very much.

**Comment by donotdespair** [comment]
Hmmm @mantihuang 

I think I have never encountered such problems with it. How about trying with its log or demeaned log? Otherwise, dropping it is also an option for this project (where data is important but we won't let it stop the progress on other aspects).

Cheers, T

**Comment by mantihuang** [comment]
Hi @donotdespair 

I have committed my latest version of code into the GitHub. However, the IRF looks weird and the Fevd is also strange (constant ).

1. I have tried to draw the IRF and fevd with the posterior draws and it works well.
2. I am not sure if the error is caused by my code about transferring B0 and B1 into A and B.
Could you check that for me? (I hope the website is also updated)

Thank you very much.

**Comment by donotdespair** [comment]
Hey @mantihuang 

Please drop by my office. Without seeing more results, like the `A` estimates it's impossible for me to guess what the problem might be.

Greetings, T

**Comment by mantihuang** [comment]
Hi @donotdespair 

Thanks ! I was planing to go to your office this afternoon.


See you then ~

Manting

**Pull request merged**
